# Generated by Django 4.2.7 on 2024-02-21 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemsDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Price', models.IntegerField(blank=True, null=True)),
                ('Des', models.CharField(blank=True, max_length=100, null=True)),
                ('Itemimg', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('spice', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewCatDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Orgin', models.CharField(blank=True, max_length=100, null=True)),
                ('Catimg', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('Desc', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
