# Generated by Django 4.2.7 on 2024-02-29 09:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FooBack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsdb',
            name='Date_data',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='newcatdb',
            name='Data_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
